### ISSUE TITLE
Issue in Practical 1

### ISSUE THREAD

**Issue by suyogschavan** [Parth1906/SPPU-2019-Pattern-SE-COMP-Fundamentals-of-Data-Structures-Practicals#8]
You've done this practical with the help of builtin SET methods which is not the correct way. Because, In the manual they've mentioned that **this should be done without builtin SET methods**. I have a program for this. Replay and I will do that if you want to.
![image](https://user-images.githubusercontent.com/83905525/209438049-7e0e0150-1a29-43f3-8309-2884697e5c13.png)
Here you can see

**Comment by HarshalDS** [comment]
Issues in flowchart....
